version: "2.16"
services:
  backend:
    build: ./backend
    ports:
    - "5000:5000"
    environment:
      FLASK_ENV: production

  web:
    build: ./monty-hall-ui
    ports:
    - "80:80"
    depends_on:
    - backend


  

