version: "3.8"
services:
  backend:
    build: ./backend
    ports:
    - "80:80"

  frontend:
    build: ./monty-hall-ui
    ports:
    - "3000:3000"
    depends_on:
    - backend
    stdin_open: true
    tty: true


  

