version: "3.8"
services:
  backend:
    build:
      context: ./backend
      tags:
        - "game-backend"
    ports:
    - "80:80"
    volumes:
      - ./backend:/app
      - /app/node_modules

  # mongodb:
  #   image: 'mongo'
  #   volumes:
  #     - data:/data/db
  #   env_file:
  #     - ./env/mongo.env

  frontend:
    build:
      context: ./frontend
      tags:
        - "game-frontend"
    ports:
    - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
    - backend
    stdin_open: true
    tty: true

# volumes:
#   data:
    


  

